bikeunit/urls.py
from django.conf.urls import url, include
from pedais import views


urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^grupos/', include('pedais.urls')),
    url(r'^contas/', include('contas.urls')),
]

contas/urls.py
from django.conf.urls import url
import contas.views as contas_views
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^envia_email_login$',
        contas_views.envia_email_login,
        name='envia_email_login'),
    url(r'^login',
        contas_views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout')
]

pedais/urls.py
from django.conf.urls import url
from pedais import views


urlpatterns = [
    url(r'^novo$', views.novo_grupo, name='novo_grupo'),
    url (r'^(\d+)/', views.view_grupo, name='view_grupo'),
]

contas/models.py
import uuid

from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(max_length=40, default=uuid.uuid4)

pedais/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Grupo(models.Model):

    def get_absolute_url(self):
        return reverse("view_grupo", args=[self.pk])


class Pedal(models.Model):
    grupo = models.ForeignKey(to='pedais.Grupo', default=None)
    destino = models.TextField(default='')

    def __str__(self):
        return self.destino

    class Meta:
        ordering = ('id', )
        unique_together = ('grupo', 'destino')

pedais/forms.py
from django.core.exceptions import ValidationError
from .models import Pedal
from django import forms

ERRO_ITEM_VAZIO = 'Este campo não pode estar vazio.'
ERRO_ITEM_DUPLICADO = 'Você já adicionou este pedal na lista.'

class PedalForm(forms.models.ModelForm):
    class Meta:
        model = Pedal
        fields = ('destino', )
        widgets = {
            'destino': forms.fields.TextInput(attrs={
                'class': 'form-control input-lg',
                'placeholder': 'Informe o destino do pedal',
            }),
        }
        error_messages = {
            'destino': {'required' : ERRO_ITEM_VAZIO}
        }

    def save(self, grupo):
        self.instance.grupo = grupo
        return super().save()

class PedalExistenteNoGrupoForm(PedalForm):

    def __init__(self, grupo, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.grupo = grupo

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e :
            e.error_dict = {'destino':[ERRO_ITEM_DUPLICADO]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

contas/views.py
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.contrib import auth, messages
from contas.models import Token
from django.core.urlresolvers import reverse

def envia_email_login(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)

    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )
    corpo_do_email = f'Use este link para logar:\n\n{url}'

    send_mail('Seu link para login no BikeUnit',
              corpo_do_email,
              'noreply@bikeunit.com', 
              [email]
    )
    messages.success(
        request,
        'Verifique seu email, te enviamos um link para que você possa acessar.'
    )
    return redirect('/')

def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

pedais/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from pedais.models import Pedal, Grupo
from pedais.forms import PedalForm, PedalExistenteNoGrupoForm


def home_page(request):
    return render(request,'home.html', {'form':PedalForm()})


def view_grupo(request, grupo_id):
    grupo = Grupo.objects.get(id=grupo_id)
    form = PedalExistenteNoGrupoForm(grupo=grupo)

    if request.method == 'POST':
        form = PedalExistenteNoGrupoForm(data=request.POST, grupo=grupo)
        if form.is_valid():
            form.save()
            return redirect(grupo)
    return render(request, 'grupo.html',{'grupo':grupo, 'form':form})

def novo_grupo(request):
    form = PedalForm(data=request.POST)
    if form.is_valid():
        grupo = Grupo.objects.create()
        form.save(grupo=grupo)
        return redirect(grupo)
    return render(request, 'home.html', {'form':form})

pedais/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BikeUnit</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">BikeUnit</a>

          
          {% if user.email %}
            <ul class="nav navbar-nav navbar-right">
              <li class="navbar-text">Logado como {{ user.email }}</li>
              <li><a href="{% url 'logout' %}">Sair</a></li>
            </ul>
            {% else %}
              <form class="navbar-form navbar-right"
                    method="POST"
                    action="{% url 'envia_email_login' %}">
                  
                <span>Informe o email para login</span>
                <input class="form-control" name="email" type="email">
                {% csrf_token %}
              </form>
          {% endif %}
            
      </nav>

      
      {% if messages %}
        <div class="row">
          <div class="col-md-8">
            
            {% for message in messages %}
              
              {% if message.level_tag == 'success' %}
                <div class="alert alert-success">{{ message }}</div>
              {% else %}
                <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
                
            {% endfor %}
              
          </div>
        </div>      
      {% endif %}
  

      <div class="row">
        <div class="col-md-12 col-lg-12 col-md-offset-3 jumbotron">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            <form method="POST" action="{% block form_action %}{% endblock %}">
              {{ form.destino }}
              {% csrf_token %}
              {% if form.errors %}
              {% for error in form.destino.errors %}
              <div class="form-group has-error alert alert-danger">
                <div class="help-block">{{ error }}</div>
              </div>
              {% endfor %}
              {% endif %}
            </form>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          {% block tabela %}
          {% endblock %}
        </div>
      </div>

    </div>
    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script src="/static/js/grupo.js"></script>

    <script>
      $(document).ready(function(){
        window.BikeUnit.inicializa()
      })
    </script>
  </body>

</html>

pedais/templates/grupo.html
{% extends "base.html" %}

{% block header_text %}Seus Pedais{% endblock header_text %}

{% block form_action %}{% url 'view_grupo' grupo.id %}{% endblock form_action %}

{% block tabela %}
<table id="id_tabela_pedais" class="table">
    {% for pedal in grupo.pedal_set.all %}
    <tr>
        <td>{{ forloop.counter }}: {{ pedal.destino }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock tabela %}

pedais/templates/home.html
{% extends "base.html" %}

{% block header_text %}BikeUnit{% endblock header_text %}

{% block form_action %}{% url 'novo_grupo' %}{% endblock form_action %}